#! /bin/bash
status_date=$(date "+%a %d/%m/%y %H:%M:%S")
status_battery=$(cat /sys/class/power_supply/BAT0/capacity)
status_brightness=$(echo "($(brightnessctl get)*100)/$(brightnessctl max)"|bc)
status_volume=$(pactl get-sink-volume @DEFAULT_SINK@ | sed -n "s/.* \([0-9]\+\)% .*/\1/p")


st -t popup -e dialog --msgbox "DATE: $status_date\nBATTERY: $status_battery%\nBRIGHTNESS: $status_brightness%\nVOLUME: $status_volume%" 10 40
